[feature] - [4] - [semver:minor] - REST-API initialized
bimser-intern/surveysaurus-service pull request #5
Opened 2022-08-08 21:15 UTC by abdullahbodur

#4

2022-08-08 23:42 UTC, MuhammedYurga submitted a review, later dismissed

2022-08-09 05:57 UTC, otipirdamaz requested changes

2022-08-09 05:57 UTC, otipirdamaz commented on rest-api/.gitignore
> +package-lock.json
package-lock.json dosyası gitignore dosyasında olmasa iyi olur. Bu dosyanın kodunuzla beraber versiyonlanması daha kullanışlı olur.

2022-08-09 06:11 UTC, abdullahbodur commented on rest-api/.gitignore
> +package-lock.json
düzeltildi

2022-08-09 06:16 UTC, otipirdamaz approved these changes

2022-08-09 07:08 UTC, MuhammedYurga approved these changes

2022-08-09 13:09 UTC, ummugulsumm approved these changes

2022-08-09 13:13 UTC, omerhamsi approved these changes

2022-08-09 15:28 UTC, merged